name: Bot3
 
on:
  push:
    branches: [ master ]

env:
  TZ: America/Recife

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 525600

    steps:
       - name: Checkouts
         uses: actions/checkout@master

       - name: Initializing Bobot Environment
         continue-on-error: true
         timeout-minutes: 100
         run: |
              git config --global user.name "Hitsuki"
              git config --global user.email "secrets.EMAILGIT"
              mkdir tmp && cd tmp
              git clone 'https://github.com/Project-WKF/Bot3-Workflow' bobot

       - name: Setup Erfan GSIs Tool
         continue-on-error: true
         timeout-minutes: 10
         run: |
              git clone --recurse-submodules https://github.com/Treble-Experience/ErfanGSIs-Hitsuki ErfanGSIs
              cd Erf*; sudo bash setup.sh

       - name: Updating packages
         continue-on-error: true
         timeout-minutes: 100
         run: |
              sudo apt-get update && apt-get upgrade -y

       - name: Setting ccache
         run: |
              mkdir -p $HOME/.ccache/
              echo 'compiler_check = none' >> $HOME/.ccache/ccache.conf
              echo "stats = false" >> $HOME/.ccache/ccache.conf
              echo 'max_size = 10G' >> $HOME/.ccache/ccache.conf
              echo "base_dir = $HOME" >> $HOME/.ccache/ccache.conf
              echo "cache_dir = $HOME/cache" >> $HOME/.ccache/ccache.conf
              echo "hash_dir = false" >> $HOME/.ccache/ccache.conf

       - name: Setup Yukosky Merger
         continue-on-error: true
         timeout-minutes: 10
         run: |
              git clone --recurse-submodules https://github.com/Treble-Experience/S_EXT-P-Merger Merger

       - name: Freeing up memory
         run: |
              docker rmi `docker images -q`
              sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php
              sudo apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php*
              sudo apt-get -y autoremove --purge
              sudo apt-get clean 

       - name: Installing apt-fast
         run: |
              sudo add-apt-repository ppa:apt-fast/stable
              sudo apt-get update
              sudo apt-get -y install apt-fast

       - name: Setup Bot3
         continue-on-error: true
         timeout-minutes: 10
         run: |
              git clone https://${{ secrets.USERNAME }}":${{ secrets.GITTOKEN }}"@github.com/Project-WKF/Bot3-Jar bobot
              mv bobot/*.jar .; rm -rf bobot
              mv *.jar BoboBot.jar

       - name: Run Bot3 in first time
         continue-on-error: true
         timeout-minutes: 3
         run: |
               java -jar BoboBot.jar
         
       - name: Add values
         continue-on-error: true
         timeout-minutes: 1
         run: |
              rm -rf configs/config.prop
              cd configs
              touch config.prop
              echo "bot-token=${{ secrets.TOKEN }}" >> "config.prop"
              echo "bot-username=HitaloSama" >> "config.prop"
              echo "bot-master=918317361" >> "config.prop"
              echo "bot-sf-pass=${{ secrets.PASSWORD }}" >> sf-creds.config
              echo "bot-sf-proj=trebleexperience" >> sf-creds.config
              echo "bot-sf-user=hitalokun" >> sf-creds.config
              echo "bot-announcement-id=-1001179583442" >> sf-creds.config
              echo "bot-sf-host=frs.sourceforge.net" >> sf-creds.config
              echo "bot-send-announcement=true" >> sf-creds.config
             
       - name: Run Bot3
         continue-on-error: true
         timeout-minutes: 350
         run: sudo java -jar BoboBot.jar
         
       - name: Loop workflow
         continue-on-error: true
         timeout-minutes: 1
         run: |
              cd tmp/bobot
              date=`date +%Y%m%d`
              echo "$date - i'm in a infernal loop" >> push.txt
              git add .
              git commit -m "[ $date ] - re-starting"
              
       - name: Reruns
         continue-on-error: true
         timeout-minutes: 5
         run: |
              cd tmp/bobot
              sudo apt-get install expect -y
              expect -c "
              spawn git push -f 
              expect \"Username\"
              send \"HitaloSama\r\"
              expect \"Password\"
              send \"${{ secrets.PASSWORD }}\r\"
              expect \"master -> master\"
              set timeout -10
              interact"
